leg_fl_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j_flhr
    - j_flhp
    - j_flkp
  gains:
    j_flhr:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_flhp:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_flkp:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
leg_fr_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j_frhr
    - j_frhp
    - j_frkp
  gains:
    j_frhr:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_frhp:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_frkp:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
leg_rl_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j_rlhr
    - j_rlhp
    - j_rlkp
  gains:
    j_rlhr:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_rlhp:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_rlkp:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
leg_rr_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j_rrhr
    - j_rrhp
    - j_rrkp
  gains:
    j_rrhr:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_rrhp:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_rrkp:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
leg_all_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - j_flhr
    - j_flhp
    - j_flkp
    - j_frhr
    - j_frhp
    - j_frkp
    - j_rlhr
    - j_rlhp
    - j_rlkp
    - j_rrhr
    - j_rrhp
    - j_rrkp
  gains:
    j_flhr:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_flhp:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_flkp:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_frhr:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_frhp:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_frkp:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_rlhr:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_rlhp:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_rlkp:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_rrhr:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_rrhp:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    j_rrkp:
      p: 100
      d: 1
      i: 1
      i_clamp: 1